// ignore_for_file: avoid_print
/// Reads GOOGLE_MAPS_API_KEY from `.env` and syncs to web + iOS.
/// Run from `client/`: `dart run tool/sync_maps_key.dart`
import 'dart:convert';
import 'dart:io';

void main() {
  final root = Directory.current;
  final envFile = File('${root.path}${Platform.pathSeparator}.env');
  if (!envFile.existsSync()) {
    print('No .env found. Create client/.env with GOOGLE_MAPS_API_KEY=...');
    exit(1);
  }
  String? key;
  for (final line in envFile.readAsLinesSync()) {
    final t = line.trim();
    if (t.isEmpty || t.startsWith('#')) continue;
    if (t.startsWith('GOOGLE_MAPS_API_KEY=')) {
      key = t.substring('GOOGLE_MAPS_API_KEY='.length).trim();
      if (key.startsWith('"') && key.endsWith('"')) {
        key = key.substring(1, key.length - 1);
      }
      break;
    }
  }
  if (key == null || key.isEmpty || key == 'YOUR_GOOGLE_MAPS_API_KEY') {
    print('GOOGLE_MAPS_API_KEY missing or placeholder in .env');
    exit(1);
  }

  // Web: JS that sets key before gmaps_loader.js runs
  final webDir = Directory('${root.path}${Platform.pathSeparator}web');
  final webConfig = File('${webDir.path}${Platform.pathSeparator}gmaps_config.js');
  final jsKey = jsonEncode(key);
  webConfig.writeAsStringSync(
    '// Generated by: dart run tool/sync_maps_key.dart\n'
    '// Restrict this key in Google Cloud (HTTP referrers for web).\n'
    'window.__TiffinGmapsKey=$jsKey;\n',
  );
  print('Wrote web/gmaps_config.js');

  // iOS: xcconfig for Info.plist GMSApiKey
  final iosFlutter = Directory(
    '${root.path}${Platform.pathSeparator}ios${Platform.pathSeparator}Flutter',
  );
  final mapsXcconfig = File(
    '${iosFlutter.path}${Platform.pathSeparator}MapsKey.xcconfig',
  );
  mapsXcconfig.writeAsStringSync(
    '// Generated by: dart run tool/sync_maps_key.dart\n'
    'GOOGLE_MAPS_API_KEY=$key\n',
  );
  print('Wrote ios/Flutter/MapsKey.xcconfig');

  print('Done. Restart flutter run (web/iOS). Android picks up .env on next gradle build.');
}
