import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

abstract final class ReceiptPdfGenerator {
  /// Generates a daily tiffin receipt PDF and returns bytes for save/share.
  static Future<Uint8List> generateReceiptPdf({
    required String customerName,
    required String customerId,
    required DateTime date,
    required List<Map<String, dynamic>> items,
    required double totalAmount,
    required String paymentStatus,
    required String businessName,
  }) async {
    final doc = pw.Document();
    final df = DateFormat('dd MMM yyyy');

    String itemName(Map<String, dynamic> i) {
      return i['name']?.toString() ??
          i['itemName']?.toString() ??
          i['slot']?.toString() ??
          'Item';
    }

    String itemQty(Map<String, dynamic> i) {
      final q = i['quantity'] ?? i['qty'] ?? 1;
      return '$q';
    }

    String itemPrice(Map<String, dynamic> i) {
      final n = i['price'] ?? i['total'] ?? i['unitPrice'] ?? 0;
      final v = n is num ? n.toDouble() : double.tryParse('$n') ?? 0;
      return 'Rs ${v.toStringAsFixed(2)}';
    }

    PdfColor statusColor(String status) {
      final s = status.toLowerCase();
      if (s.contains('paid') || s.contains('success')) return PdfColors.green700;
      if (s.contains('pending')) return PdfColors.orange700;
      return PdfColors.red700;
    }

    doc.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(24),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                businessName,
                style: pw.TextStyle(
                  fontSize: 22,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Daily Tiffin Receipt',
                style: const pw.TextStyle(fontSize: 12),
              ),
              pw.SizedBox(height: 10),
              pw.Divider(),
              pw.SizedBox(height: 8),
              pw.Text('Customer: $customerName'),
              pw.Text('Customer ID: $customerId'),
              pw.Text('Date: ${df.format(date)}'),
              pw.SizedBox(height: 12),
              pw.TableHelper.fromTextArray(
                headers: const ['Item name', 'Qty', 'Price'],
                data: items
                    .map((e) => <String>[itemName(e), itemQty(e), itemPrice(e)])
                    .toList(),
                border: pw.TableBorder.all(color: PdfColors.grey500, width: 0.8),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                cellPadding: const pw.EdgeInsets.symmetric(
                  vertical: 6,
                  horizontal: 6,
                ),
                columnWidths: {
                  0: const pw.FlexColumnWidth(3),
                  1: const pw.FlexColumnWidth(1),
                  2: const pw.FlexColumnWidth(1.5),
                },
              ),
              pw.SizedBox(height: 10),
              pw.Divider(),
              pw.SizedBox(height: 8),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                children: [
                  pw.Text(
                    'Total: Rs ${totalAmount.toStringAsFixed(2)}',
                    style: pw.TextStyle(
                      fontSize: 13,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                ],
              ),
              pw.SizedBox(height: 8),
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: statusColor(paymentStatus)),
                  borderRadius: pw.BorderRadius.circular(4),
                ),
                child: pw.Text(
                  'Payment status: ${paymentStatus.isEmpty ? 'Pending' : paymentStatus}',
                  style: pw.TextStyle(
                    color: statusColor(paymentStatus),
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
              pw.Spacer(),
              pw.Center(
                child: pw.Text(
                  'Thank you for your business',
                  style: const pw.TextStyle(fontSize: 11),
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Center(
                child: pw.Text(
                  'Generated by Tiffin CRM',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
                ),
              ),
            ],
          );
        },
      ),
    );

    return doc.save();
  }
}

